### ISSUE TITLE
exception when creating a newbuild for 59.0rc

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/releasewarrior-2.0#86]
(rw) ➜  releasewarrior-2.0 git:(master) r newbuild firefox 59.0rc
WARNING: no release data state file
INFO: ensuring releasewarrior repo is up to date and in sync with origin
INFO: generating wiki from template and config
INFO: writing to data file: /home/bhearsum/repos/releasewarrior-data/inflight/firefox/firefox-release-rc-59.0rc.json
INFO: writing to wiki file: /home/bhearsum/repos/releasewarrior-data/inflight/firefox/firefox-release-rc-59.0rc.md
Traceback (most recent call last):
  File "/home/bhearsum/.virtualenvs/rw/bin/release", line 11, in <module>
    load_entry_point('releasewarrior', 'console_scripts', 'release')()
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bhearsum/repos/releasewarrior-2.0/releasewarrior/cli.py", line 118, in newbuild
    write_and_commit(data, data_path, wiki_path, commit_msg, logger, config)
  File "/home/bhearsum/repos/releasewarrior-2.0/releasewarrior/wiki_data.py", line 171, in write_and_commit
    corsica = generate_corsica(config, logger)
  File "/home/bhearsum/repos/releasewarrior-2.0/releasewarrior/wiki_data.py", line 160, in generate_corsica
    return template.render(**corsica_data)
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/Jinja2-2.9.6-py3.6.egg/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/Jinja2-2.9.6-py3.6.egg/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/Jinja2-2.9.6-py3.6.egg/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/Jinja2-2.9.6-py3.6.egg/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/bhearsum/repos/releasewarrior-2.0/releasewarrior/templates/corsica/index.template.html", line 25, in top-level template code
    {{ release_status()|indent(4) }}
  File "/home/bhearsum/.virtualenvs/rw/lib/python3.6/site-packages/Jinja2-2.9.6-py3.6.egg/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/home/bhearsum/repos/releasewarrior-2.0/releasewarrior/templates/corsica/index.template.html", line 23, in template
    {% include "corsica/firefox_release_progress.template.html" %}
  File "/home/bhearsum/repos/releasewarrior-2.0/releasewarrior/templates/corsica/firefox_release_progress.template.html", line 23, in top-level template code
    {% if releases["firefox"]["release"]["human_tasks"]["publish"] %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'publish'

**Comment by mozbhearsum** [comment]
s/publish/ship in the corsica template seems to fix it - I'll put together a PR.

**Comment by mozbhearsum** [comment]
PR is #87
